name: Test OIDC Token

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      test_environment:
        description: 'Environment to test'
        required: false
        default: 'dev'

jobs:
  test-oidc-token:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required to fetch the OIDC token
      contents: read  # Standard permission for workflows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate OIDC Token
      id: oidc-token
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        echo "Fetching OIDC token for testing..."
        TOKEN=$(curl -X POST -H "Authorization: Bearer $ACTIONS_ID_TOKEN" \
          "https://token.actions.githubusercontent.com" \
          -d \
          '{
            "aud": "google",
            "sub": "repository:${GITHUB_REPOSITORY}:ref:${GITHUB_REF}"
          }')
        echo "OIDC Token:"
        echo "${TOKEN}" > oidc_token.txt
      env:
        ACTIONS_ID_TOKEN: ${{ secrets.ACTIONS_ID_TOKEN }}

  - Further task extra

